#
# This is a conda build config file.
#
# For details on these settings, see:
# https://docs.conda.io/projects/conda-build/en/latest/resources/variants.html
#
# To use this file in conjunction with the 'publish-conda-stack' tool,
# your specs file should start with these lines:
#
#   shared-config:
#     master-conda-build-config: master-conda-build-config.yaml
#

libboost_devel:
  - '1.86'
hdf5:
  - 1.10.6
jsoncpp:
  - 1.9.4
numpy:
  - 1.17
python:
  - 3.7

pin_run_as_build:
  boost:
    max_pin: x.x.x
  boost_cpp:
    max_pin: x.x.x
  hdf5:
    max_pin: x.x.x
  jsoncpp:
    max_pin: x.x.x
  numpy:
    max_pin: x.x
  python:
    max_pin: x.x

CONDA_BUILD_SYSROOT:
  - /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk
